/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javatest;

import java.util.Scanner;

import javatest.UI.CafeUI;
import javatest.service.CafeService;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        Scanner scanner = new Scanner(System.in);

        CafeService service = new CafeService();

        CafeUI ui = new CafeUI(scanner, service);
        
        ui.displaywithPosition();
    }
}
